spring.application.name=ScentOfASA
spring.profiles.default=h2
server.port=${PORT:8080}
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
spring.flyway.locations=classpath:db/migration
