CREATE TABLE public_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_date DATE NOT NULL,
    time_slot VARCHAR(5) NOT NULL,
    guide_language VARCHAR(10) NOT NULL,
    guest_count INT NOT NULL,
    customer_name VARCHAR(120) NOT NULL,
    customer_email VARCHAR(255) NOT NULL,
    customer_phone VARCHAR(40),
    notes VARCHAR(1000),
    reservation_status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uk_public_reservations_slot
    ON public_reservations (reservation_date, time_slot, guide_language);
