CREATE TABLE admin_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_date DATE NOT NULL,
    time_slot VARCHAR(5) NOT NULL,
    guide_language VARCHAR(10) NOT NULL,
    guide_name VARCHAR(120),
    slot_status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uk_admin_slots_date_time_language
    ON admin_slots (slot_date, time_slot, guide_language);
