CREATE TABLE guide_staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id VARCHAR(80) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    guide_language VARCHAR(10) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uk_guide_staff_login_id
    ON guide_staff (login_id);

CREATE INDEX idx_guide_staff_language_active
    ON guide_staff (guide_language, active);

ALTER TABLE admin_slots
    ADD COLUMN guide_staff_id BIGINT;

ALTER TABLE admin_slots
    ADD CONSTRAINT fk_admin_slots_guide_staff
    FOREIGN KEY (guide_staff_id) REFERENCES guide_staff (id);

CREATE INDEX idx_admin_slots_guide_staff_id
    ON admin_slots (guide_staff_id);

INSERT INTO guide_staff (login_id, password_hash, display_name, guide_language, active, created_at, updated_at)
VALUES
    ('guide_en_1', 'TEMP_RESET_REQUIRED', 'English Guide 1', 'en', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('guide_en_2', 'TEMP_RESET_REQUIRED', 'English Guide 2', 'en', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('guide_en_3', 'TEMP_RESET_REQUIRED', 'English Guide 3', 'en', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('guide_ja_1', 'TEMP_RESET_REQUIRED', 'Japanese Guide 1', 'ja', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('guide_ja_2', 'TEMP_RESET_REQUIRED', 'Japanese Guide 2', 'ja', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('guide_ja_3', 'TEMP_RESET_REQUIRED', 'Japanese Guide 3', 'ja', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
